version: '3'

volumes:
  postgres_data: {}

services:
  posgres:
    image: postgres:14.1
    container_name: deliveryhunt_postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
